version: '3.3'
services:
  inscricaoescola:
    build: .
    ports:
      - "82:80"
    volumes:
      - ./:/usr/share/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
  mysql-app:
    image: mariadb:10.3
    ports:
      - "3307:3306"
    volumes:
      - ./docker/dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    networks:
      - app-network
  phpmyadmin:
    depends_on:
      - mysql-app
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql-app
    networks:
       - app-network
networks:
  app-network:
    driver: bridge
