version: '3.3'
services:
  inscricaoescola:
    build: .
    ports:
      - "82:80"
    volumes:
      - ./:/usr/share/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    #      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
  mysql-app:
    image: mysql:8.0.27
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: "dbinscricaoescola"
      MYSQL_ROOT_PASSWORD: "password"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
