<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class EscolaridadeRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'modulo_id' => 'required',
            'nivel_escolaridade' => 'required|string|max:33',
        ];
    }

    public function messages(): array
    {
        return ([
            'modulo_id.required' => 'É obrigatório selecionar a escolaridade.',
            'nivel_escolaridade.required' => 'O campo serié é obrigatório.'

        ]); // TODO: Change the autogenerated stub
    }
}
