<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class PontuacaoReprovar extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
            'motivo_recusar.*' => 'max:500'
        ];
    }

     public function messages()
     {
         return ([
             'motivo_recusar.*.max' => 'O tamanho máximo de caracteres é de 500!',
         ]); // TODO: Change the autogenerated stub
     }
}
