<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class Recurso extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
            'CPF' => 'required',
            'comentario' => 'required|max:500'
        ];
    }

    public function messages()
    {
        return ([
            'CPF.required' => 'O campo CPF é obrigatório ser preenchido!',
            'comentario.required' => 'É necessário descrever o recurso!',
            'comentario.max' => 'Não é possível ultrapassar o limite  de caracteres!',
        ]); // TODO: Change the autogenerated stub
    }
}
