<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Support\MessageBag;
use Illuminate\View\Middleware\ShareErrorsFromSession;

class Registro extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'nome_aluno' => 'required|string|min:10|max:50',
            'data_nascimento_aluno' => 'required|date',
            'nome_mae'=> 'string|min:10|max:50',
            'cpf_mae' => 'cpf|formato_cpf',
            'telefone_mae' => 'celular_com_ddd',
            'nome_pai' => 'string|min:10|max:50',
            'cpf_pai' => 'cpf|formato_cpf',
            'telefone_pai' => 'celular_com_ddd',
            'nome_responsavel' => 'required|string|min:10|max:50',
            'cpf_responsavel' => 'required|cpf|formato_cpf',
            'telefone_reponsavel' => 'required|celular_com_ddd',
            'email_responsavel' => 'required|string|max:100',
            'serie' => 'required|exists:serie,id'
        ];
    }

    public function messages()
    {
        return ([
            'nome_aluno.required' => 'O campo nome do aluno é obrigatório.',
            'data_nascimento_aluno' => 'O campo data de nascimento do aluno é obrigatório',
            'nome_responsavel' => 'O campo nome do responsalvel é obrigatório',
            'cpf_responsavel' => 'O campo cpf do responsalvel é obrigatório',
            'telefone_reponsavel' => 'O campo telefone do responsalvel é obrigatório',
            'email_responsavel' => 'O campo email do responsalvel é obrigatório',
            'serie.exists' => 'Você deve selecionar as série do aluno',

        ]); // TODO: Change the autogenerated stub
    }
}
